FROM teste_compilado

# RUN git clone https://github.com/joaovicentesouto/INE5418.git
# RUN zsh /INE5418/install.sh
# RUN ls
# RUN zsh /distr/install.sh

CMD ["./INE5418/build/distributed_systems/distributed_systems_executable", "1"]