FROM joaovicentesouto/artful_boost_1_67

RUN git clone https://github.com/joaovicentesouto/INE5418.git
RUN zsh /INE5418/install.sh

CMD ["./INE5418/build/distributed_systems/distributed_systems_executable", "1"]