FROM ubuntu

RUN apt-get update && apt-get install -y build-essential \
    cmake \
    libboost-all-dev \
    git \
    vim \
    zsh \
    zlib1g-dev libbz2-dev libsnappy-dev libpthread-stubs0-dev \
    && apt-get clean