version: '2'

services:

  cont0:
    extends:
      file: base-service.yml
      service: base
    container_name: container0
    hostname: container0
    environment:
      - ID=0
      - HIBERNATION_TIME=1
    tty: true                  # iterative

  cont1:
    extends:
      file: base-service.yml
      service: base
    container_name: container1
    hostname: container1
    depends_on:
      - cont0
    environment:
      - ID=1
      - HIBERNATION_TIME=3
    tty: true                  # iterative

  cont2:
    extends:
      file: base-service.yml
      service: base
    container_name: container2
    hostname: container2
    depends_on:
      - cont0
    environment:
      - ID=2
      - HIBERNATION_TIME=5
    tty: true                  # iterative